[tool.poetry]
name = "senseclust"
version = "0.0.1"
description = "Clustering of Finnish word senses"
authors = ["Frankie Robertson <frankie@robertson.name>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
nltk = "*"
sklearn = "*"
numpy = "*"
scipy = "*"
matplotlib = "*"
click = ">=7"
finntk = ">=0.0.14"
fastcluster = "*"
networkx = "*"
wikiparse = {git = "https://github.com/frankier/wikiparse.git"}
stiff = {git = "https://github.com/frankier/stiff.git"}
paramiko = "^2.4"
expcomb = {git = "https://github.com/frankier/expcomb.git", commit = "ff7f1f5b7bd2e86284f5e0e68ed121e58f72f6ef"}
snakemake = "^5.5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
