[tool.poetry]
name = "senseclust"
version = "0.0.1"
description = "Clustering of Finnish word senses"
authors = ["Frankie Robertson <frankie@robertson.name>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
nltk = "*"
sklearn = "*"
numpy = "*"
scipy = "*"
matplotlib = "*"
click = ">=7"
finntk = ">=0.0.62"
fastcluster = "*"
networkx = "*"
wikiparse = {git = "https://github.com/frankier/wikiparse.git"}
stiff = {git = "https://github.com/frankier/stiff.git"}
paramiko = "^2.4"
expcomb = {git = "https://github.com/frankier/expcomb.git", commit = "3aabcd75ac3c69ad0b501e6bf100c923d1ae1094"}
snakemake = "^5.5.4"
vecstorenn = {git = "https://github.com/frankier/vecstorenn.git"}
sentence-transformers = "^0.2.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
